/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 food_kiwi_01_4k.gltf -t -r public
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    food_kiwi_01: THREE.Mesh;
  };
  materials: {
    food_kiwi_01: THREE.MeshStandardMaterial;
  };
};

export function Kiwi(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/kiwi/food_kiwi_01_4k.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.food_kiwi_01.geometry}
        material={materials.food_kiwi_01}
      />
    </group>
  );
}

useGLTF.preload("/models/kiwi/food_kiwi_01_4k.gltf");
