/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform --types
Author: MRX (https://sketchfab.com/visitingskipertv)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shop-8013212d71a2438088e1049533d39744
Title: Shop
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["Cylinder002_12_-_Default_0"]: THREE.Mesh;
    ["Cylinder002_14_-_Default_0"]: THREE.Mesh;
    ["GeoSphere001_13_-_Default_0"]: THREE.Mesh;
    ["Cylinder003_12_-_Default_0"]: THREE.Mesh;
    ["Cylinder003_14_-_Default_0"]: THREE.Mesh;
    ["GeoSphere002_13_-_Default_0"]: THREE.Mesh;
    ["Box010_15_-_Default_0"]: THREE.Mesh;
    TextPlus001__0: THREE.Mesh;
    ["Box011_15_-_Default_0"]: THREE.Mesh;
    ["Box011_17_-_Default_0"]: THREE.Mesh;
    ["Box011_16_-_Default_0"]: THREE.Mesh;
    ["Box011_18_-_Default_0"]: THREE.Mesh;
    ["Box002_12_-_Default_0"]: THREE.Mesh;
    ["Box002_06_-_Default_0"]: THREE.Mesh;
    ["Box012_15_-_Default_0"]: THREE.Mesh;
    ["Box012_17_-_Default_0"]: THREE.Mesh;
    ["Box012_16_-_Default_0"]: THREE.Mesh;
    ["Box012_18_-_Default_0"]: THREE.Mesh;
    ["Box001_06_-_Default_0"]: THREE.Mesh;
    ["Box001_06_-_Default_0_1"]: THREE.Mesh;
    ["Box001_04_-_Default_0"]: THREE.Mesh;
    ["Box001_05_-_Default_0"]: THREE.Mesh;
    ["Box001_02_-_Default_0"]: THREE.Mesh;
    ["Box007_05_-_Default_0"]: THREE.Mesh;
    ["Box009_05_-_Default_0"]: THREE.Mesh;
    ["Box009_01_-_Default_0"]: THREE.Mesh;
    ["Box009_Material_#176_0"]: THREE.Mesh;
    ["Box009_Material_#175_0"]: THREE.Mesh;
    ["Box009_Material_#179_0"]: THREE.Mesh;
    ["Box008_05_-_Default_0"]: THREE.Mesh;
    ["Box008_01_-_Default_0"]: THREE.Mesh;
    ["Box008_Material_#176_0"]: THREE.Mesh;
    ["Box008_Material_#175_0"]: THREE.Mesh;
    ["Box008_Material_#179_0"]: THREE.Mesh;
    ["Box005_01_-_Default_0"]: THREE.Mesh;
    ["Box006_01_-_Default_0"]: THREE.Mesh;
    ["Cylinder001_07_-_Default_0"]: THREE.Mesh;
    ["Box004_01_-_Default_0"]: THREE.Mesh;
    ["Box003_08_-_Default_0"]: THREE.Mesh;
    ["Box013_21_-_Default_0"]: THREE.Mesh;
    ["Box013_22_-_Default_0"]: THREE.Mesh;
    ["Cylinder004_23_-_Default_0"]: THREE.Mesh;
    ["Cylinder005_23_-_Default_0"]: THREE.Mesh;
    ["Cylinder006_23_-_Default_0"]: THREE.Mesh;
    ["Cylinder007_23_-_Default_0"]: THREE.Mesh;
    ["Cylinder008_23_-_Default_0"]: THREE.Mesh;
    ["Cylinder009_23_-_Default_0"]: THREE.Mesh;
  };
  materials: {
    ["12_-_Default"]: THREE.MeshStandardMaterial;
    ["14_-_Default"]: THREE.MeshStandardMaterial;
    ["13_-_Default"]: THREE.MeshStandardMaterial;
    ["15_-_Default"]: THREE.MeshStandardMaterial;
    TextPlus001__0: THREE.MeshStandardMaterial;
    ["17_-_Default"]: THREE.MeshStandardMaterial;
    ["16_-_Default"]: THREE.MeshStandardMaterial;
    ["18_-_Default"]: THREE.MeshStandardMaterial;
    ["06_-_Default"]: THREE.MeshStandardMaterial;
    ["04_-_Default"]: THREE.MeshStandardMaterial;
    ["05_-_Default"]: THREE.MeshStandardMaterial;
    ["01_-_Default"]: THREE.MeshStandardMaterial;
    Material_176: THREE.MeshStandardMaterial;
    ["07_-_Default"]: THREE.MeshStandardMaterial;
    ["08_-_Default"]: THREE.MeshStandardMaterial;
    ["21_-_Default"]: THREE.MeshStandardMaterial;
    ["23_-_Default"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/scene/scene-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[22.06, -2.54, 47.29]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes["Cylinder002_12_-_Default_0"].geometry}
          material={materials["12_-_Default"]}
        />
        <mesh
          geometry={nodes["Cylinder002_14_-_Default_0"].geometry}
          material={materials["14_-_Default"]}
        />
      </group>
      <group position={[-13.12, -2.54, 47.29]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes["Cylinder003_12_-_Default_0"].geometry}
          material={materials["12_-_Default"]}
        />
        <mesh
          geometry={nodes["Cylinder003_14_-_Default_0"].geometry}
          material={materials["14_-_Default"]}
        />
      </group>
      <group
        position={[37.34, 0.2, 28.47]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.45]}
      >
        <mesh
          geometry={nodes["Box011_15_-_Default_0"].geometry}
          material={materials["15_-_Default"]}
        />
        <mesh
          geometry={nodes["Box011_17_-_Default_0"].geometry}
          material={materials["17_-_Default"]}
        />
        <mesh
          geometry={nodes["Box011_16_-_Default_0"].geometry}
          material={materials["16_-_Default"]}
        />
        <mesh
          geometry={nodes["Box011_18_-_Default_0"].geometry}
          material={materials["18_-_Default"]}
        />
      </group>
      <group
        position={[4.68, -2.61, -0.13]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1.05, 1.05, 0.07]}
      >
        <mesh
          geometry={nodes["Box002_12_-_Default_0"].geometry}
          material={materials["12_-_Default"]}
        />
        <mesh
          geometry={nodes["Box002_06_-_Default_0"].geometry}
          material={materials["06_-_Default"]}
        />
      </group>
      <group
        position={[-28.33, 0.2, 28.47]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 0.45]}
      >
        <mesh
          geometry={nodes["Box012_15_-_Default_0"].geometry}
          material={materials["15_-_Default"]}
        />
        <mesh
          geometry={nodes["Box012_17_-_Default_0"].geometry}
          material={materials["17_-_Default"]}
        />
        <mesh
          geometry={nodes["Box012_16_-_Default_0"].geometry}
          material={materials["16_-_Default"]}
        />
        <mesh
          geometry={nodes["Box012_18_-_Default_0"].geometry}
          material={materials["18_-_Default"]}
        />
      </group>
      <group position={[4.68, 0.02, -0.1]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes["Box001_06_-_Default_0"].geometry}
          material={materials["06_-_Default"]}
        />
        <mesh
          geometry={nodes["Box001_06_-_Default_0_1"].geometry}
          material={materials["06_-_Default"]}
        />
        <mesh
          geometry={nodes["Box001_04_-_Default_0"].geometry}
          material={materials["04_-_Default"]}
        />
        <mesh
          geometry={nodes["Box001_05_-_Default_0"].geometry}
          material={materials["05_-_Default"]}
        />
        <mesh
          geometry={nodes["Box001_02_-_Default_0"].geometry}
          material={materials.TextPlus001__0}
        />
      </group>
      <group position={[-27.2, 31.58, 41.41]} scale={[1, 0.19, 1]}>
        <mesh
          geometry={nodes["Box009_05_-_Default_0"].geometry}
          material={materials["05_-_Default"]}
        />
        <mesh
          geometry={nodes["Box009_01_-_Default_0"].geometry}
          material={materials["01_-_Default"]}
        />
        <mesh
          geometry={nodes["Box009_Material_#176_0"].geometry}
          material={materials.Material_176}
        />
        <mesh
          geometry={nodes["Box009_Material_#175_0"].geometry}
          material={materials.Material_176}
        />
        <mesh
          geometry={nodes["Box009_Material_#179_0"].geometry}
          material={materials.Material_176}
        />
      </group>
      <group position={[37.16, 31.58, 41.41]} scale={[1, 0.19, 1]}>
        <mesh
          geometry={nodes["Box008_05_-_Default_0"].geometry}
          material={materials["05_-_Default"]}
        />
        <mesh
          geometry={nodes["Box008_01_-_Default_0"].geometry}
          material={materials["01_-_Default"]}
        />
        <mesh
          geometry={nodes["Box008_Material_#176_0"].geometry}
          material={materials.Material_176}
        />
        <mesh
          geometry={nodes["Box008_Material_#175_0"].geometry}
          material={materials.Material_176}
        />
        <mesh
          geometry={nodes["Box008_Material_#179_0"].geometry}
          material={materials.Material_176}
        />
      </group>
      <group
        position={[33.44, 41.69, -3.2]}
        rotation={[-1.57, 0, 0]}
        scale={[0.82, 0.74, 0.74]}
      >
        <mesh
          geometry={nodes["Box013_21_-_Default_0"].geometry}
          material={materials["21_-_Default"]}
        />
        <mesh
          geometry={nodes["Box013_22_-_Default_0"].geometry}
          material={materials["07_-_Default"]}
        />
      </group>
      <mesh
        geometry={nodes["GeoSphere001_13_-_Default_0"].geometry}
        material={materials["13_-_Default"]}
        position={[21.97, 4.61, 47.34]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 2.13]}
      />
      <mesh
        geometry={nodes["GeoSphere002_13_-_Default_0"].geometry}
        material={materials["13_-_Default"]}
        position={[-13.21, 4.61, 47.34]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[1, 1, 2.13]}
      />
      <mesh
        geometry={nodes["Box010_15_-_Default_0"].geometry}
        material={materials["15_-_Default"]}
        position={[5.39, -2.55, 49.41]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.TextPlus001__0.geometry}
        material={materials.TextPlus001__0}
        position={[5.65, -2.18, 50.71]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.16}
      />
      <mesh
        geometry={nodes["Box007_05_-_Default_0"].geometry}
        material={materials["05_-_Default"]}
        position={[-2.2, 12.9, 41.75]}
        scale={[1, 1, 0.57]}
      />
      <mesh
        geometry={nodes["Box005_01_-_Default_0"].geometry}
        material={materials["01_-_Default"]}
        position={[-32.11, 48.42, -12.16]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        geometry={nodes["Box006_01_-_Default_0"].geometry}
        material={materials["01_-_Default"]}
        position={[-32.11, 48.42, -17.81]}
        rotation={[-1.57, 0, 0]}
      />
      <mesh
        geometry={nodes["Cylinder001_07_-_Default_0"].geometry}
        material={materials["07_-_Default"]}
        position={[-22.25, 48.56, -15.43]}
        rotation={[-1.57, 0, 0]}
        scale={[1.06, 1.06, 0.95]}
      />
      <mesh
        geometry={nodes["Box004_01_-_Default_0"].geometry}
        material={materials["01_-_Default"]}
        position={[-25.53, 42.84, -15.03]}
        rotation={[-1.54, 0, 0]}
        scale={[0.88, 0.66, 3.99]}
      />
      <mesh
        geometry={nodes["Box003_08_-_Default_0"].geometry}
        material={materials["08_-_Default"]}
        position={[-25.37, 41.72, -15.05]}
        rotation={[-1.57, 0, 0]}
        scale={[1, 0.8, 0.73]}
      />
      <mesh
        geometry={nodes["Cylinder004_23_-_Default_0"].geometry}
        material={materials["23_-_Default"]}
        position={[36.12, 41.55, 10.73]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.75}
      />
      <mesh
        geometry={nodes["Cylinder005_23_-_Default_0"].geometry}
        material={materials["23_-_Default"]}
        position={[33.5, 41.55, 10.73]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.75}
      />
      <mesh
        geometry={nodes["Cylinder006_23_-_Default_0"].geometry}
        material={materials["23_-_Default"]}
        position={[30.89, 41.55, 10.73]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={0.75}
      />
      <mesh
        geometry={nodes["Cylinder007_23_-_Default_0"].geometry}
        material={materials["23_-_Default"]}
        position={[36.12, 41.55, -17.42]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[-0.75, 0.75, 0.75]}
      />
      <mesh
        geometry={nodes["Cylinder008_23_-_Default_0"].geometry}
        material={materials["23_-_Default"]}
        position={[33.5, 41.55, -17.42]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[-0.75, 0.75, 0.75]}
      />
      <mesh
        geometry={nodes["Cylinder009_23_-_Default_0"].geometry}
        material={materials["23_-_Default"]}
        position={[30.89, 41.55, -17.42]}
        rotation={[-Math.PI / 2, 0, Math.PI / 2]}
        scale={[-0.75, 0.75, 0.75]}
      />
    </group>
  );
}

useGLTF.preload("/models/scene/scene-transformed.glb");
